### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character (...)

### ISSUE THREAD

**Issue by AfkF24** [baieric/chatstats#9]
Hi,

I've been having some issues with getting some of the graphs to generate due to an encoding issue I suppose. I'm dumping my whole logs here so hopefully you can get a better idea on what's going on. https://pastebin.com/VgBqT7hx

Thanks for the great tool!

**Comment by baieric** [comment]
Hi, thanks for trying out ChatStats! Just wanted to let you know I saw this and will take a closer look on the weekend :)

**Comment by baieric** [comment]
Hey @AfkF24 - are you using a Windows device? I looked up the error and it's because Windows cannot render emojis in the console. I had some non-essential code that printed your top emojis in the console for the emoji graph, so I just updated the code to not do that on Windows.

To be honest I did not test the code at all, so I'd appreciate if you let me know if it worked!

**Comment by AfkF24** [comment]
Hi, using the updated grapher.py and adding `import sys` worked, as it was complaining regarding that (`NameError: name 'sys' is not defined`).

Thank you once again for your awesome work and the quick fix. Much appreciated!

**Comment by baieric** [comment]
ahh oops, I should have caught that. Thank you for letting me know! Glad it's working now.
